server:
  port: 9527

spring:
  application:
    name: auth-gateway
  profiles:
    active: dev
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        # 认证中心
        - id: auth-center
          uri: lb://auth-center
          predicates:
            - Path=/auth/**
          filters:
            # 验证码处理
            - CacheRequest
            - ImgCodeFilter
            - StripPrefix=1
        #system 模块
        - id: auth-system
          uri: lb://auth-system
          predicates:
            - Path=/system/**
          filters:
            # 限流配置
            - StripPrefix=1




eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:8001/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true     #访问路径可以显示IP地址